# Generated by Django 3.1.7 on 2021-02-25 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('jumlah_halaman', models.IntegerField()),
                ('penerbit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('jumlah_hari', models.IntegerField()),
                ('buku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjamans', to='bukus.buku')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjamans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('denda', models.BigIntegerField(null=True)),
                ('peminjaman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengembalian', to='bukus.peminjaman')),
            ],
        ),
    ]
