# Generated by Django 2.1 on 2021-03-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=30, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='jumlah_halaman',
            field=models.IntegerField(verbose_name='Jumlah Halaman'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='penerbit',
            field=models.CharField(max_length=30, verbose_name='Penerbit'),
        ),
    ]
